### ISSUE TITLE
Minimal Example

### ISSUE THREAD

**Issue by MaryAnnEbeling** [pstjohn/pyefm#2]
I would like to use your code with one of my cobra models to calculate EFVs, but I have no idea, where to start. Can you provide a minimal example? Thanks!

**Comment by pstjohn** [comment]
Sure, just added one:  [pyefm/test/Example.ipynb](https://github.com/pstjohn/pyefm/blob/master/test/Example.ipynb)

The package relies a lot on the [cobrapy])http://opencobra.github.io/cobrapy) package, so definitely check that out. Also, it largely just wraps the efmtool java dependency, that might be tricky to get working

Feel free to re-open if that doesn't work!
